package com.example.famekodriver.core.utils

object ImageLinks {
    const val ANI_SIGNUP = "https://i.postimg.cc/QtcVL4Vw/ani-signup.png"
    const val DELIVERY = "https://i.postimg.cc/VNrdgL8p/delivery.jpg"
    const val IC_ABOBOYAA = "https://i.postimg.cc/W1fd0qQB/ic-aboboyaa.jpg"
    const val IC_BICYCLE = "https://i.postimg.cc/vZS45xJG/ic-bicycle.jpg"
    const val IC_CAR_SALOON = "https://i.postimg.cc/Mprn1fCS/ic-car-saloon.png"
    const val IC_FAMEKO_LOGO = "https://i.postimg.cc/CLmRpwJt/ic-fameko-logo.jpg"
    const val IC_FAMEKO_DRIVER_LOGO = "https://i.postimg.cc/m2QSY1Lz/ic-fameko-driver-logo.jpg"
    const val IC_OKADA = "https://i.postimg.cc/nrxnBdGN/motorbike-removebg-preview.png"
    const val IC_PRAGYA = "https://i.postimg.cc/1znfB5S1/ic-praggia.jpg"
    const val IC_TRUCK = "https://i.postimg.cc/cJgrh4WN/ic-truck.jpg"
    const val DRIVER_SIGNUP_BG = "https://i.postimg.cc/dtpd96tY/driver-signup.png"
    const val DRIVER_SPLASH_SCREEN = "https://i.postimg.cc/7ZY4rB4k/5.jpg"
    const val CUSTOMER_SPLASH_SCREEN = "https://i.postimg.cc/NjftvNcW/1.jpg"
    const val CUSTOMER_LOGIN_CAROUSEL_1 = "https://i.postimg.cc/dVHYs8sx/8.jpg"
    const val CUSTOMER_LOGIN_CAROUSEL_2 = "https://i.postimg.cc/2S8YNHYN/2.jpg"
    const val CUSTOMER_LOGIN_CAROUSEL_3 = "https://i.postimg.cc/zGXNYdN1/3.jpg"
    const val DRIVER_LOGIN_CAROUSEL_1 = "https://i.postimg.cc/dVHYs8sx/8.jpg"
    const val DRIVER_LOGIN_CAROUSEL_2 = "https://i.postimg.cc/nhRJFvFW/7.jpg"
    const val DRIVER_LOGIN_CAROUSEL_3 = "https://i.postimg.cc/K8vbh9bb/6.jpg"
    const val MILLIE_LOGIN = "https://i.postimg.cc/pTKyNGyS/millie-login.png"
    const val RENTAL = "https://i.postimg.cc/5tY6gNJ2/rental.jpg"
    const val RIDE = "https://i.postimg.cc/CKBz7L0R/ride.jpg"
}
